project:
  type: book
  output-dir: _book

# Specify the chapters of the book
chapters:
  - index.qmd           # Introduction or Overview
  - Errors.qmd          # Chapter on handling Errors
  - ICT issues.qmd      # Specific ICT Issues and Solutions

format:
  html:
    theme:
      - cosmo            # Theme for styling

