# Define the main document structure and output settings
output-dir: _output  # Optional: Specify output directory, or leave this out for root output

format:
  html:
    theme: cosmo               # Set your desired theme
    css: styles.css            # Optional custom CSS for styling
    toc: true                  # Include a Table of Contents if needed
    toc-depth: 2               # Depth for the TOC
    code-link: true            # Enable links for code snippets
    colorlinks: true           # Use colored hyperlinks for readability

# Optional font customization
font-family:
  main: "Kingster, Arial, sans-serif"    # Body text font
  headings: "Avenir, Futura, sans-serif" # Heading font
